# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for mangaba-agent.

Produces a ``--onedir`` bundle containing the ``mangaba`` CLI executable plus
all bundled data (dashboard SPA, TUI dist, skills, plugins, locales, tool
manifest).

Build prerequisites (run before pyinstaller):
    python scripts/gen_tool_manifest.py
    cd web && npm install && npm run build
    cd ui-tui && npm install && npm run build

Usage:
    pyinstaller mangaba-agent.spec --noconfirm
"""

from pathlib import Path

import sys

block_cipher = None
ROOT = Path(".").resolve()

# ---------------------------------------------------------------------------
# Data files to include in the bundle
# ---------------------------------------------------------------------------
datas = []

# Dashboard SPA (Vite build output)
web_dist = ROOT / "mangaba_cli" / "web_dist"
if web_dist.is_dir():
    datas.append((str(web_dist), "mangaba_cli/web_dist"))

# TUI prebuilt (Ink/React compiled JS)
tui_dist = ROOT / "mangaba_cli" / "tui_dist"
if tui_dist.is_dir():
    datas.append((str(tui_dist), "mangaba_cli/tui_dist"))

# Bundled skills
skills_dir = ROOT / "skills"
if skills_dir.is_dir():
    datas.append((str(skills_dir), "skills"))

# Optional skills
optional_skills_dir = ROOT / "optional-skills"
if optional_skills_dir.is_dir():
    datas.append((str(optional_skills_dir), "optional-skills"))

# i18n locales
locales_dir = ROOT / "locales"
if locales_dir.is_dir():
    datas.append((str(locales_dir), "locales"))

# Bundled plugins (plugin.yaml + __init__.py for each)
plugins_dir = ROOT / "plugins"
if plugins_dir.is_dir():
    datas.append((str(plugins_dir), "plugins"))

# Gateway assets (images, etc.)
gateway_assets = ROOT / "gateway" / "assets"
if gateway_assets.is_dir():
    datas.append((str(gateway_assets), "gateway/assets"))

# Tool manifest (generated by scripts/gen_tool_manifest.py)
tool_manifest = ROOT / "tools" / "_tool_manifest.json"
if tool_manifest.is_file():
    datas.append((str(tool_manifest), "tools"))

# Mangaba CLI scripts (install helpers)
cli_scripts = ROOT / "mangaba_cli" / "scripts"
if cli_scripts.is_dir():
    datas.append((str(cli_scripts), "mangaba_cli/scripts"))

# ---------------------------------------------------------------------------
# Hidden imports — modules loaded dynamically via plugin/provider/tool
# discovery, lazy imports, or importlib that PyInstaller can't trace.
# ---------------------------------------------------------------------------
hiddenimports = [
    # ── Core ────────────────────────────────────────────────────────────
    "mangaba_agent.frozen",
    "mangaba_agent.mangaba_bootstrap",
    "mangaba_agent.mangaba_constants",
    "mangaba_agent.mangaba_logging",
    "mangaba_agent.mangaba_state",
    "mangaba_agent.mangaba_time",
    "mangaba_agent.run_agent",
    "mangaba_agent.cli",
    "mangaba_agent.model_tools",
    "mangaba_agent.toolsets",
    "mangaba_agent.toolset_distributions",
    "mangaba_agent.batch_runner",
    "mangaba_agent.trajectory_compressor",
    "mangaba_agent.utils",
    "mangaba_agent.mcp_serve",
    "mangaba_agent.mini_swe_runner",

    # ── CLI ─────────────────────────────────────────────────────────────
    "mangaba_cli.main",
    "mangaba_cli._parser",
    "mangaba_cli.config",
    "mangaba_cli.plugins",
    "mangaba_cli.skin_engine",
    "mangaba_cli.setup",
    "mangaba_cli.banner",
    "mangaba_cli.curator",
    "mangaba_cli.kanban",
    "mangaba_cli.kanban_db",
    "mangaba_cli.cron",
    "mangaba_cli.doctor",
    "mangaba_cli.gateway",
    "mangaba_cli.web_server",
    "mangaba_cli.env_loader",
    "mangaba_cli.fallback_config",
    "mangaba_cli.pt_input_extras",
    "mangaba_cli.colors",
    "mangaba_cli.commands",
    "mangaba_cli.completion",
    "mangaba_cli.profiles",
    "mangaba_cli.models",
    "mangaba_cli.model_catalog",
    "mangaba_cli.model_normalize",
    "mangaba_cli.model_switch",
    "mangaba_cli.status",
    "mangaba_cli.debug",
    "mangaba_cli.dump",
    "mangaba_cli.backup",
    "mangaba_cli.migrate",
    "mangaba_cli.uninstall",
    "mangaba_cli.relaunch",
    "mangaba_cli.pty_bridge",
    "mangaba_cli.voice",
    "mangaba_cli.send_cmd",
    "mangaba_cli.session_recap",
    "mangaba_cli.goals",
    "mangaba_cli.inventory",
    "mangaba_cli.fleet",
    "mangaba_cli.checkpoints",
    "mangaba_cli.clipboard",
    "mangaba_cli.tips",
    "mangaba_cli.hooks",
    "mangaba_cli.guardrails",
    "mangaba_cli.usage_ledger",
    "mangaba_cli.rate_limit_log",
    "mangaba_cli.trace_ledger",
    "mangaba_cli.tools_config",
    "mangaba_cli.skills_config",
    "mangaba_cli.skills_hub",
    "mangaba_cli.secrets_cli",
    "mangaba_cli.security_advisories",
    "mangaba_cli.security_scan",
    "mangaba_cli.portal_cli",
    "mangaba_cli.pairing",
    "mangaba_cli.platforms",
    "mangaba_cli.plugins_cmd",
    "mangaba_cli.curses_ui",
    "mangaba_cli.cli_output",
    "mangaba_cli.callbacks",
    "mangaba_cli.api_clients",
    "mangaba_cli.bundles",
    "mangaba_cli.dep_ensure",
    "mangaba_cli.default_soul",
    "mangaba_cli.timeouts",
    "mangaba_cli.memory_setup",
    "mangaba_cli.auth",
    "mangaba_cli.auth_commands",
    "mangaba_cli.copilot_auth",
    "mangaba_cli.dingtalk_auth",
    "mangaba_cli.vercel_auth",
    "mangaba_cli.whatsapp_cloud",
    "mangaba_cli.slack_cli",
    "mangaba_cli.nous_subscription",
    "mangaba_cli.agent_templates",
    "mangaba_cli.browser_connect",
    "mangaba_cli.claw",
    "mangaba_cli.xai_retirement",
    "mangaba_cli.azure_detect",
    "mangaba_cli.codex_models",
    "mangaba_cli.codex_runtime_plugin_migration",
    "mangaba_cli.codex_runtime_switch",
    "mangaba_cli.profile_describer",
    "mangaba_cli.profile_distribution",
    "mangaba_cli.client_profiles",
    "mangaba_cli.providers",
    "mangaba_cli.runtime_provider",
    "mangaba_cli.oneshot",
    "mangaba_cli.fallback_cmd",
    "mangaba_cli.gateway_windows",
    "mangaba_cli.kanban_decompose",
    "mangaba_cli.kanban_diagnostics",
    "mangaba_cli.kanban_specify",
    "mangaba_cli.kanban_swarm",
    "mangaba_cli._subprocess_compat",
    "mangaba_cli.stdio",
    "mangaba_cli.proxy",
    "mangaba_cli.proxy.cli",
    "mangaba_cli.proxy.server",

    # ── Agent internals ─────────────────────────────────────────────────
    "agent.display",
    "agent.prompt_builder",
    "agent.system_prompt",
    "agent.context_engine",
    "agent.context_compressor",
    "agent.conversation_compression",
    "agent.conversation_loop",
    "agent.memory_manager",
    "agent.memory_provider",
    "agent.skill_utils",
    "agent.skill_commands",
    "agent.skill_preprocessing",
    "agent.skill_bundles",
    "agent.process_bootstrap",
    "agent.auxiliary_client",
    "agent.image_gen_provider",
    "agent.image_gen_registry",
    "agent.video_gen_provider",
    "agent.video_gen_registry",
    "agent.web_search_provider",
    "agent.web_search_registry",
    "agent.browser_provider",
    "agent.browser_registry",
    "agent.curator",
    "agent.curator_backup",
    "agent.credential_pool",
    "agent.credential_sources",
    "agent.iteration_budget",
    "agent.tool_executor",
    "agent.tool_dispatch_helpers",
    "agent.tool_guardrails",
    "agent.tool_result_classification",
    "agent.title_generator",
    "agent.followups",
    "agent.onboarding",
    "agent.i18n",
    "agent.redact",
    "agent.insights",
    "agent.rate_limit_tracker",
    "agent.retry_utils",
    "agent.error_classifier",
    "agent.file_safety",
    "agent.message_sanitization",
    "agent.model_capability",
    "agent.model_metadata",
    "agent.markdown_tables",
    "agent.request_planner",
    "agent.agent_init",
    "agent.agent_runtime_helpers",
    "agent.async_utils",
    "agent.shell_hooks",
    "agent.subdirectory_hints",
    "agent.stream_diag",
    "agent.think_scrubber",
    "agent.manual_compression_feedback",
    "agent.context_references",
    "agent.instincts",
    "agent.instinct_extraction",
    "agent.portal_tags",
    "agent.plugin_llm",
    "agent.background_review",
    "agent.chat_completion_helpers",
    "agent.usage_pricing",
    "agent.account_usage",
    "agent.nous_rate_guard",
    "agent.lmstudio_reasoning",
    "agent.image_routing",
    "agent.moonshot_schema",
    "agent.codex_runtime",
    "agent.models_dev",
    "agent.anthropic_adapter",
    "agent.bedrock_adapter",
    "agent.azure_identity_adapter",
    "agent.gemini_native_adapter",
    "agent.gemini_cloudcode_adapter",
    "agent.gemini_schema",
    "agent.codex_responses_adapter",
    "agent.google_code_assist",
    "agent.google_oauth",
    "agent.copilot_acp_client",

    # ── Tools (self-registering via registry.register) ──────────────────
    "tools.browser_cdp_tool",
    "tools.browser_dialog_tool",
    "tools.browser_tool",
    "tools.clarify_tool",
    "tools.code_execution_tool",
    "tools.computer_use_tool",
    "tools.cronjob_tools",
    "tools.delegate_tool",
    "tools.discord_tool",
    "tools.feishu_doc_tool",
    "tools.feishu_drive_tool",
    "tools.file_tools",
    "tools.homeassistant_tool",
    "tools.image_generation_tool",
    "tools.kanban_tools",
    "tools.memory_tool",
    "tools.mixture_of_agents_tool",
    "tools.process_registry",
    "tools.send_message_tool",
    "tools.session_search_tool",
    "tools.skill_manager_tool",
    "tools.skills_hub_tool",
    "tools.skills_tool",
    "tools.terminal_tool",
    "tools.todo_tool",
    "tools.tts_tool",
    "tools.video_generation_tool",
    "tools.vision_tools",
    "tools.web_tools",
    "tools.x_search_tool",
    "tools.yuanbao_tools",

    # ── Tool environments ───────────────────────────────────────────────
    "tools.environments.base",
    "tools.environments.local",
    "tools.environments.docker",
    "tools.environments.ssh",
    "tools.environments.modal",
    "tools.environments.modal_utils",
    "tools.environments.managed_modal",
    "tools.environments.daytona",
    "tools.environments.singularity",
    "tools.environments.vercel_sandbox",
    "tools.environments.file_sync",

    # ── Model providers (29 dirs) ──────────────────────────────────────
    "plugins.model_providers.ai_gateway",
    "plugins.model_providers.alibaba",
    "plugins.model_providers.alibaba_coding_plan",
    "plugins.model_providers.anthropic",
    "plugins.model_providers.arcee",
    "plugins.model_providers.azure_foundry",
    "plugins.model_providers.bedrock",
    "plugins.model_providers.copilot",
    "plugins.model_providers.copilot_acp",
    "plugins.model_providers.custom",
    "plugins.model_providers.deepseek",
    "plugins.model_providers.gemini",
    "plugins.model_providers.gmi",
    "plugins.model_providers.huggingface",
    "plugins.model_providers.kilocode",
    "plugins.model_providers.kimi_coding",
    "plugins.model_providers.minimax",
    "plugins.model_providers.nous",
    "plugins.model_providers.novita",
    "plugins.model_providers.nvidia",
    "plugins.model_providers.ollama_cloud",
    "plugins.model_providers.openai_codex",
    "plugins.model_providers.opencode_zen",
    "plugins.model_providers.openrouter",
    "plugins.model_providers.qwen_oauth",
    "plugins.model_providers.stepfun",
    "plugins.model_providers.xai",
    "plugins.model_providers.xiaomi",
    "plugins.model_providers.zai",

    # ── Memory providers ────────────────────────────────────────────────
    "plugins.memory.byterover",
    "plugins.memory.hindsight",
    "plugins.memory.holographic",
    "plugins.memory.honcho",
    "plugins.memory.mangaba_rag",
    "plugins.memory.mem0",
    "plugins.memory.openviking",
    "plugins.memory.retaindb",
    "plugins.memory.supermemory",

    # ── Gateway platforms ───────────────────────────────────────────────
    "gateway.platforms.api_server",
    "gateway.platforms.base",
    "gateway.platforms.bluebubbles",
    "gateway.platforms.dingtalk",
    "gateway.platforms.email",
    "gateway.platforms.feishu",
    "gateway.platforms.feishu_comment",
    "gateway.platforms.feishu_comment_rules",
    "gateway.platforms.helpers",
    "gateway.platforms.homeassistant",
    "gateway.platforms.matrix",
    "gateway.platforms.mattermost",
    "gateway.platforms.msgraph_webhook",
    "gateway.platforms.signal",
    "gateway.platforms.signal_rate_limit",
    "gateway.platforms.slack",
    "gateway.platforms.sms",
    "gateway.platforms.telegram",
    "gateway.platforms.telegram_network",
    "gateway.platforms.webhook",
    "gateway.platforms.wecom",
    "gateway.platforms.wecom_callback",
    "gateway.platforms.wecom_crypto",
    "gateway.platforms.weixin",
    "gateway.platforms.whatsapp",
    "gateway.platforms.yuanbao",
    "gateway.platforms.yuanbao_media",
    "gateway.platforms.yuanbao_proto",
    "gateway.platforms.yuanbao_sticker",
    "gateway.platforms.qqbot",
    "gateway.platforms.qqbot.adapter",
    "gateway.platforms.qqbot.chunked_upload",
    "gateway.platforms.qqbot.constants",
    "gateway.platforms.qqbot.crypto",
    "gateway.platforms.qqbot.keyboards",
    "gateway.platforms.qqbot.onboard",
    "gateway.platforms.qqbot.utils",

    # ── Plugin platforms ────────────────────────────────────────────────
    "plugins.platforms.discord",
    "plugins.platforms.discord.adapter",
    "plugins.platforms.google_chat",
    "plugins.platforms.google_chat.adapter",
    "plugins.platforms.google_chat.oauth",
    "plugins.platforms.irc",
    "plugins.platforms.irc.adapter",
    "plugins.platforms.line",
    "plugins.platforms.line.adapter",
    "plugins.platforms.simplex",
    "plugins.platforms.simplex.adapter",
    "plugins.platforms.teams",
    "plugins.platforms.teams.adapter",

    # ── Other plugins ───────────────────────────────────────────────────
    "plugins.context_engine",
    "plugins.browser.browserbase",
    "plugins.browser.browser_use",
    "plugins.browser.firecrawl",
    "plugins.image_gen.fal",
    "plugins.image_gen.openai",
    "plugins.image_gen.openai_codex",
    "plugins.image_gen.xai",
    "plugins.video_gen.fal",
    "plugins.video_gen.xai",
    "plugins.web.brave_free",
    "plugins.web.ddgs",
    "plugins.web.exa",
    "plugins.web.firecrawl",
    "plugins.web.parallel",
    "plugins.web.searxng",
    "plugins.web.tavily",
    "plugins.web.xai",
    "plugins.disk_cleanup",
    "plugins.google_meet",
    "plugins.spotify",
    "plugins.teams_pipeline",
    "plugins.observability.langfuse",

    # ── Cron ────────────────────────────────────────────────────────────
    "cron",
    "cron.jobs",
    "cron.nl_schedule",
    "cron.scheduler",

    # ── TUI gateway ─────────────────────────────────────────────────────
    "tui_gateway",
    "tui_gateway.entry",
    "tui_gateway.event_publisher",
    "tui_gateway.render",
    "tui_gateway.server",
    "tui_gateway.slash_worker",
    "tui_gateway.transport",
    "tui_gateway.ws",

    # ── ACP adapter ─────────────────────────────────────────────────────
    "acp_adapter",
    "acp_adapter.auth",
    "acp_adapter.edit_approval",
    "acp_adapter.entry",
    "acp_adapter.events",
    "acp_adapter.permissions",
    "acp_adapter.server",
    "acp_adapter.session",
    "acp_adapter.tools",

    # ── Providers (legacy) ──────────────────────────────────────────────
    "providers",
    "providers.base",

    # ── Gateway core ────────────────────────────────────────────────────
    "gateway.channel_directory",
    "gateway.config",
    "gateway.delivery",
    "gateway.display_config",
    "gateway.hooks",
    "gateway.memory_monitor",
    "gateway.mirror",
    "gateway.pairing",
    "gateway.platform_registry",
    "gateway.restart",
    "gateway.run",
    "gateway.runtime_footer",
    "gateway.session",
    "gateway.session_context",
    "gateway.shutdown_forensics",
    "gateway.slash_access",
    "gateway.status",
    "gateway.sticker_cache",
    "gateway.stream_consumer",
    "gateway.whatsapp_identity",

    # ── Native extensions (PyInstaller often misses these) ──────────────
    "psutil",
    "fitz",
    "PyMuPDF",
    "pydantic",
    "pydantic_core",
    "yaml",
    "rich",
    "rich.console",
    "rich.panel",
    "rich.markdown",
    "prompt_toolkit",
    "prompt_toolkit.patch_stdout",
    "openai",
    "httpx",
    "httpx_socks",
    "tenacity",
    "croniter",
    "jinja2",
    "jwt",
    "dotenv",
    "ruamel",
    "ruamel.yaml",

    # ── Speech-to-text (faster-whisper) ──────────────────────────────────
    # Bundled directly rather than left to tools/lazy_deps.py's runtime
    # pip-install path: that path shells out to `sys.executable -m pip`,
    # which is the frozen .exe itself in a PyInstaller build (no real
    # python.exe / pip module available to invoke), so the lazy-install
    # can never succeed once frozen. Bundling here is the only way STT
    # works out of the box in mangaba.exe / mangaba-dashboard.exe.
    # Adds real size (numpy + onnxruntime + ctranslate2 + PyAV) but the
    # voice feature would otherwise be silently broken for every user of
    # the packaged installer, not just an edge case.
    "faster_whisper",
    "ctranslate2",
    "av",
    "tokenizers",
    "huggingface_hub",
    "onnxruntime",
    "sounddevice",
    "numpy",
]

# ---------------------------------------------------------------------------
# Modules to exclude (heavy, unused in core build)
# ---------------------------------------------------------------------------
excludes = [
    "tkinter",
    "matplotlib",
    # numpy is NOT excluded -- faster-whisper (bundled above for STT) needs
    # it at import time.
    "pandas",
    "scipy",
    "PIL",
    "cv2",
    "torch",
    "tensorflow",
    "notebook",
    "IPython",
    "pytest",
    "unittest",
]

# ---------------------------------------------------------------------------
# Analysis
# ---------------------------------------------------------------------------
a = Analysis(
    [str(ROOT / "mangaba_cli" / "main.py")],
    pathex=[str(ROOT)],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excludes,
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

# ---------------------------------------------------------------------------
# Executable: mangaba (main CLI)
# ---------------------------------------------------------------------------
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="mangaba",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    # UPX packing is a strong AV false-positive trigger for PyInstaller
    # binaries (SPEC_INSTALLER.md Fase 5) — off on all targets; costs
    # ~5-10MB per exe, worth it for fewer "Trojan:Win32/..." flags.
    upx=False,
    console=True,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="mangaba",
)

# ---------------------------------------------------------------------------
# Executable: mangaba-acp (ACP adapter for editors)
# ---------------------------------------------------------------------------
exe_acp = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="mangaba-acp",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=True,
)

coll_acp = COLLECT(
    exe_acp,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="mangaba-acp",
)

# ---------------------------------------------------------------------------
# Executable: mangaba-dashboard (windowed — no console window)
# ---------------------------------------------------------------------------
# Built with console=False so double-clicking opens the dashboard
# silently (no terminal flash).  stdout/stderr are redirected to a
# log file inside MANGABA_HOME/logs/ by main.py when running windowed.
exe_dashboard = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="mangaba-dashboard",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    icon=str(ROOT / "installer" / "assets" / "icon.ico"),
)

coll_dashboard = COLLECT(
    exe_dashboard,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="mangaba-dashboard",
)

# ---------------------------------------------------------------------------
# Executable: mangaba-launcher (system tray — Windows installer only)
# ---------------------------------------------------------------------------
# Windows-only for now: pystray's Linux backend (AppIndicator3/GTK) needs
# system libs (libappindicator3-dev) not present on CI runners or verified
# in this build environment, and macOS's rumps/AppKit backend is likewise
# untested here. Gating avoids silently breaking the Linux/macOS legs of
# the existing build matrix over an unverified new target — see
# SPEC_INSTALLER.md's cross-platform section for the (separate, deferred)
# Linux/macOS packaging work.
if sys.platform == "win32":
    # Separate Analysis from the shared `a` above: pystray/Pillow are only
    # needed here, and pulling them into the shared PYZ would bloat the CLI/
    # ACP/dashboard bundles that don't use a tray icon. See SPEC_INSTALLER.md
    # Fase 7. `pystray`/`Pillow` must be installed (optional extra "launcher")
    # for this Analysis to resolve — absent locally, PyInstaller silently
    # fails to bundle the module rather than erroring the build (same failure
    # mode documented for the `croniter`/messaging deps gap earlier).
    a_launcher = Analysis(
        [str(ROOT / "mangaba_cli" / "launcher" / "__main__.py")],
        pathex=[str(ROOT)],
        binaries=[],
        datas=[
            (
                str(ROOT / "mangaba_cli" / "launcher" / "resources"),
                "mangaba_cli/launcher/resources",
            ),
        ],
        hiddenimports=["pystray", "PIL", "PIL.Image", "customtkinter", "darkdetect"],
        hookspath=[],
        hooksconfig={},
        runtime_hooks=[],
        # NOT the shared `excludes` above — that list excludes "PIL" (correct
        # for the CLI/ACP/dashboard bundles, which don't need it), which
        # would silently win over the hiddenimports here and ship a launcher
        # with no Pillow, crashing on the first `import pystray` (pystray
        # itself depends on PIL for icon rendering).
        excludes=["matplotlib", "numpy", "pandas", "scipy", "cv2",
                  "torch", "tensorflow", "notebook", "IPython", "pytest",
                  "unittest"],
        win_no_prefer_redirects=False,
        win_private_assemblies=False,
        cipher=block_cipher,
        noarchive=False,
    )

    pyz_launcher = PYZ(a_launcher.pure, a_launcher.zipped_data, cipher=block_cipher)

    exe_launcher = EXE(
        pyz_launcher,
        a_launcher.scripts,
        [],
        exclude_binaries=True,
        name="mangaba-launcher",
        debug=False,
        bootloader_ignore_signals=False,
        strip=False,
        upx=False,
        console=False,
        icon=str(ROOT / "installer" / "assets" / "icon.ico"),
    )

    coll_launcher = COLLECT(
        exe_launcher,
        a_launcher.binaries,
        a_launcher.zipfiles,
        a_launcher.datas,
        strip=False,
        upx=False,
        upx_exclude=[],
        name="mangaba-launcher",
    )

